services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beehive-admin-api
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_PORT
      - PORT:-8080
      - ALLOWED_HEADERS
      - ALLOWED_METHODS
      - ALLOWED_ORIGINS
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    volumes:
      - ./.env:/app/.env

  session-store:
    image: redis:7.2.4-alpine3.19
    container_name: beehive-admin-session-store
    ports:
      - ${SESSION_STORE_PORT:-6379}:${SESSION_STORE_PORT:-6379}
